@baseUrl = http://localhost:3001
#@baseUrl = https://phonebook-helsinkifullstack3-1x.onrender.com

# Get all persons
GET {{baseUrl}}/api/persons

###

# Get a person
GET {{baseUrl}}/api/persons/3

###

# Get a nonexisting person
GET {{baseUrl}}/api/persons/9000

###

# Get info
GET {{baseUrl}}/info


###

#Delete person 1
DELETE {{baseUrl}}/api/persons/1

###

#Post person to server (remember epty line between header and request body)
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name": "Wuffeli Tryffeli",
    "number": "040 3621 4269"
}