#@baseUrl = http://localhost:3003
#@baseUrl = https://phonebook-helsinkifullstack3-1x.onrender.com
@baseUrl = https://roopemaatta-humble-sniffle-7g7pqv564pwhrpp-3003.app.github.dev

# Get all blogs
GET {{baseUrl}}/api/blogs

###

#Post blog to server (remember empty line between header and request body)
POST {{baseUrl}}/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ild1ZmxlIEF1dGhvciIsImlkIjoiNjU2NzM3ZTY1NjFmMTM3OWQwYmJmYjQzIiwiaWF0IjoxNzEyOTA3OTg1LCJleHAiOjE3MTI5MTE1ODV9.5koJS8SKYar7hLb8sa5JpAHqHm7VNYmSi6A77vW4UYw

{
    "title": "THIS BOOK IS WUFFLES PRIVATE BOOK3333",
    "author": "LeWriter2",
    "url": "www.PRIVATE.com/Hiss",
    "likes": 4,
}

###

#Delete blog from server (change id to a blog that is in the database)
DELETE  {{baseUrl}}/api/blogs/65411f0bb16b7c6adbc0f799
Authorization: bearer 65411f23b16b7c6adbc0f79f


