#@baseUrl = http://localhost:3003
#@baseUrl = https://phonebook-helsinkifullstack3-1x.onrender.com
@baseUrl = https://roopemaatta-humble-sniffle-7g7pqv564pwhrpp-3003.app.github.dev


POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "username": "Wufle Author",
    "password": "f5dsf"
    
}

###


POST {{baseUrl}}/api/login
Content-Type: application/json

{
    "username": "ErrorBakawuf",
    "password": "WrongPotato"
    
}

###

