#@baseUrl = http://localhost:3003
#@baseUrl = https://phonebook-helsinkifullstack3-1x.onrender.com
@baseUrl = https://roopemaatta-humble-sniffle-7g7pqv564pwhrpp-3003.app.github.dev


# Get all blogs
GET {{baseUrl}}/api/testing

###

#Post blog to server (remember empty line between header and request body)
POST {{baseUrl}}/reset
Content-Type: application/json

{
    "username": "Bakawuf",
    "name": "LeWriter2",
    "password": "f5dsf"
    
}

###

